### PR TITLE
ShadingPlugin: use full deps, including platform

### PR DESCRIPTION
**Pull request by kitbellew**
Otherwise, native and sjs dependencies will not be found and included in the output jar.

### CODE REVIEW

**Comment by kitbellew** [comment]
@alexarchambault @guizmaii @tgodzik please review, merge and release :)

**Review by tgodzik — APPROVED** [review]
Looks good to me, but I have never touched the code here. @alexarchambault what do you think?

**Comment by kitbellew** [comment]
@tgodzik i built a local snapshot and used for the scalameta build, and the sjs jar was built correctly. no other testing.

**Comment by kitbellew** [comment]
@tgodzik @alexarchambault added scripted tests.

as usual (with me), please review one commit at a time; each commit passes all tests.

**Comment by kitbellew** [comment]
@tgodzik how comfortable are you merging and then releasing this? I'm less worried about the change itself but previous release failed to publish, not sure if it was a temporary error.

**Comment by tgodzik** [comment]
> @tgodzik how comfortable are you merging and then releasing this? I'm less worried about the change itself but previous release failed to publish, not sure if it was a temporary error.

We'll need to have a look then. Let's merge this for now

**Comment by kitbellew** [comment]
@tgodzik @alexarchambault  https://github.com/coursier/sbt-shading/actions/runs/5655097359/job/15319591503

```
[info] gpg: no default secret key: No secret key
[info] gpg: signing failed: No secret key
Error:  java.lang.RuntimeException: Failure running 'gpg --batch --pinentry-mode loopback --passphrase *** --detach-sign --armor --use-agent --output /home/runner/work/sbt-shading/sbt-shading/target/scala-2.12/sbt-1.0/sbt-shading-2.1.3.pom.asc /home/runner/work/sbt-shading/sbt-shading/target/scala-2.12/sbt-1.0/sbt-shading-2.1.3.pom'.  Exit code: 2
```

strange. `ci.yml` hasn't changed much since https://github.com/coursier/sbt-shading/commit/84f11df179ee3f4237b3d06f5465929b9595aa27 but this gpg part seems to have stopped working. did the secret get deleted?

**Comment by tgodzik** [comment]
I don't have access to secrets so not sure if it exists or is incorrect. We'll need Alexandre's help here.

**Comment by kitbellew** [comment]
@alexarchambault is this something you could help with? @tgodzik and i can't figure out why the publish job continues failing, so we can't release any versions of this plugin.

**Comment by kitbellew** [comment]
@tgodzik @alexarchambault ok, we are officially stuck. i somehow imagined that a snapshot would be sufficient, and today it has vanished, with all scalameta builds promptly failing. @alexarchambault is there any way you could help with releasing this?

**Comment by alexarchambault** [comment]
So the release is [ongoing](https://github.com/coursier/sbt-shading/actions/runs/6174253301/job/16758444871). Seems https://github.com/coursier/sbt-shading/commit/59a67058fada300fe7f4ae15bde250810a6e4e40 fixed the GPG issues (and an earlier update of the key and secret).

**Comment by kitbellew** [comment]
@alexarchambault thank you!

**Comment by tgodzik** [comment]
Thanks!

**Pull request merged**
