### PR TITLE
add validEntries setting

### LINKED ISSUE #2: Cannot ignore entries under no package
When shading an artifact I would like to ignore the `LICENSE` and `NOTICE` entries.

Writing
```scala
validNamespaces ++= Set("LICENSE", "NOTICE")
```
does not work because of
https://github.com/coursier/sbt-shading/blob/895e7f7d73a5e25bbd3aad8f3886303ccdf58a76/src/main/scala/coursier/ShadingPlugin.scala#L204

### PR DESCRIPTION
**Pull request by adpi2**
Fixes #2

### CODE REVIEW

**Review by alexarchambault — APPROVED** [review]
Thanks @adpi2!

**Comment by adpi2** [comment]
@alexarchambault thanks for merging. Would it be possible to release? I would like to use it to fix https://github.com/sbt/sbt/issues/6402.

**Comment by adpi2** [comment]
Thanks!

**Comment by alexarchambault** [comment]
There should have been a release, scala steward saw one : https://github.com/alexarchambault/plotly-scala/pull/276

**Pull request merged**
